/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.customer;

import java.awt.event.ActionEvent;
import javax.swing.Timer;
import library.*;

/**
 *
 * @author ercan
 */
public class Home extends javax.swing.JPanel {

    final private swing.Home frame;
    Timer timer;

    /**
     * Creates new form Home
     *
     * @param home Dynamic panel.
     */
    public Home(swing.Home home) {
        initComponents();
        frame = home;

        timer = new Timer(2000, (ActionEvent e) -> {
            mainLabel.setText("Welcome " + Data.getCustomer().getId().getFullName());
            mainLabel2.setText("Card: " + Data.getCustomer().showCardNumber());
        });
        timer.setInitialDelay(0);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        mainLabel2 = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        withdrawalButton = new java.awt.Button();
        withdrawalIcon = new javax.swing.JLabel();
        depositButton = new java.awt.Button();
        depositIcon = new javax.swing.JLabel();
        balanceButton = new java.awt.Button();
        balanceIcon = new javax.swing.JLabel();
        settingsButton = new java.awt.Button();
        settingsIcon = new javax.swing.JLabel();
        transferButton = new java.awt.Button();
        transferIcon = new javax.swing.JLabel();
        transactionsButton = new java.awt.Button();
        transactionsIcon = new javax.swing.JLabel();
        logoutButton = new java.awt.Button();
        logoutIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(71, 120, 197));
        setMaximumSize(new java.awt.Dimension(1070, 590));
        setMinimumSize(new java.awt.Dimension(1070, 590));
        setPreferredSize(new java.awt.Dimension(1070, 590));

        mainLabel.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        mainLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mainLabel.setText("Welcome User");

        mainLabel2.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        mainLabel2.setForeground(new java.awt.Color(133, 187, 101));
        mainLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mainLabel2.setText("Card Num: 1234567891234567");
        mainLabel2.setMaximumSize(new java.awt.Dimension(223, 47));
        mainLabel2.setMinimumSize(new java.awt.Dimension(223, 47));
        mainLabel2.setPreferredSize(new java.awt.Dimension(223, 47));

        infoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("You can select the actions to do from below.");

        withdrawalButton.setBackground(new java.awt.Color(23, 35, 51));
        withdrawalButton.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        withdrawalButton.setForeground(new java.awt.Color(255, 255, 255));
        withdrawalButton.setLabel("Withdrawal");
        withdrawalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalButtonActionPerformed(evt);
            }
        });

        withdrawalIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_request_money_48px.png"))); // NOI18N

        depositButton.setBackground(new java.awt.Color(23, 35, 51));
        depositButton.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        depositButton.setForeground(new java.awt.Color(255, 255, 255));
        depositButton.setLabel("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        depositIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_initiate_money_transfer_48px.png"))); // NOI18N

        balanceButton.setBackground(new java.awt.Color(23, 35, 51));
        balanceButton.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        balanceButton.setForeground(new java.awt.Color(255, 255, 255));
        balanceButton.setLabel("Balance");
        balanceButton.setMinimumSize(new java.awt.Dimension(80, 49));
        balanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceButtonActionPerformed(evt);
            }
        });

        balanceIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_refund_48px.png"))); // NOI18N

        settingsButton.setBackground(new java.awt.Color(23, 35, 51));
        settingsButton.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        settingsButton.setForeground(new java.awt.Color(255, 255, 255));
        settingsButton.setLabel("Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        settingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_automatic_48px.png"))); // NOI18N

        transferButton.setBackground(new java.awt.Color(23, 35, 51));
        transferButton.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        transferButton.setForeground(new java.awt.Color(255, 255, 255));
        transferButton.setLabel("Transfer");
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        transferIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_online_money_transfer_48px.png"))); // NOI18N

        transactionsButton.setBackground(new java.awt.Color(23, 35, 51));
        transactionsButton.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        transactionsButton.setForeground(new java.awt.Color(255, 255, 255));
        transactionsButton.setLabel("Transactions");
        transactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsButtonActionPerformed(evt);
            }
        });

        transactionsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_transaction_list_48px.png"))); // NOI18N

        logoutButton.setBackground(new java.awt.Color(23, 35, 51));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setLabel("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_exit_48px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(300, 300, 300))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(settingsIcon)
                                .addGap(511, 511, 511))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(withdrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(withdrawalIcon)
                                .addGap(538, 538, 538)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(transactionsIcon)
                                        .addGap(10, 10, 10)
                                        .addComponent(transactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(transferIcon)
                                        .addGap(10, 10, 10)
                                        .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(depositIcon))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(balanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(balanceIcon)
                                .addGap(170, 170, 170)
                                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170)
                                .addComponent(logoutIcon)
                                .addGap(10, 10, 10)
                                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(mainLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainLabel)
                    .addComponent(mainLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(transferButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withdrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withdrawalIcon, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(depositIcon))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(transactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)))
                            .addComponent(transactionsIcon)))
                    .addComponent(transferIcon))
                .addGap(41, 41, 41)
                .addComponent(settingsIcon)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceIcon)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutIcon))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalButtonActionPerformed
        if (timer != null) {
            timer.stop();
        }
        frame.ChangeJPanel("WithdrawalCustomer");
    }//GEN-LAST:event_withdrawalButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        if (timer != null) {
            timer.stop();
        }
        frame.ChangeJPanel("DepositCustomer");
    }//GEN-LAST:event_depositButtonActionPerformed

    private void transactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsButtonActionPerformed
        if (timer != null) {
            timer.stop();
        }
        frame.ChangeJPanel("TransactionsCustomer");
    }//GEN-LAST:event_transactionsButtonActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        if (timer != null) {
            timer.stop();
        }
        frame.ChangeJPanel("TransferCustomer");
    }//GEN-LAST:event_transferButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        if (timer != null) {
            timer.stop();
        }
        frame.ChangeJPanel("SettingsCustomer");
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void balanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceButtonActionPerformed
        if (timer != null) {
            timer.stop();
        }
        frame.ChangeJPanel("BalanceCustomer");
    }//GEN-LAST:event_balanceButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        Data.setCustomer(null);
        if (timer != null) {
            timer.stop();
        }
        frame.ChangeJPanel("LoginCustomer");
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button balanceButton;
    private javax.swing.JLabel balanceIcon;
    private java.awt.Button depositButton;
    private javax.swing.JLabel depositIcon;
    private javax.swing.JLabel infoLabel;
    private java.awt.Button logoutButton;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel mainLabel2;
    private java.awt.Button settingsButton;
    private javax.swing.JLabel settingsIcon;
    private java.awt.Button transactionsButton;
    private javax.swing.JLabel transactionsIcon;
    private java.awt.Button transferButton;
    private javax.swing.JLabel transferIcon;
    private java.awt.Button withdrawalButton;
    private javax.swing.JLabel withdrawalIcon;
    // End of variables declaration//GEN-END:variables
}
